# Generated by Django 4.0.1 on 2022-01-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.CharField(choices=[(7, 7), (9, 9), (10, 10), (2, 2), (1, 1)], max_length=2, verbose_name='공격자 선택 숫자'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.CharField(blank=True, choices=[(8, 8), (3, 3), (6, 6), (6, 6), (3, 3)], max_length=2, verbose_name='수비자 선택 숫자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(null=True, verbose_name='포인트'),
        ),
    ]
