# Generated by Django 3.2 on 2022-01-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.IntegerField(blank=True, choices=[(2, 2), (3, 3), (8, 8), (9, 9), (10, 10)], verbose_name='공격자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.IntegerField(blank=True, choices=[(4, 4), (5, 5), (7, 7), (9, 9), (10, 10)], null=True, verbose_name='수비자 선택'),
        ),
    ]
