# Generated by Django 4.0.1 on 2022-01-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0002_alter_game_attacker_num_alter_game_defender_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='point',
        ),
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.CharField(choices=[(1, 1), (2, 2), (10, 10), (6, 6), (7, 7)], max_length=2, verbose_name='공격자 선택 숫자'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.CharField(blank=True, choices=[(5, 5), (11, 11), (3, 3), (5, 5), (5, 5)], max_length=2, verbose_name='수비자 선택 숫자'),
        ),
    ]
