# Generated by Django 3.1.3 on 2022-01-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0002_alter_game_attacker_num_alter_game_defender_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.IntegerField(blank=True, choices=[(2, 2), (3, 3), (4, 4), (6, 6), (10, 10)], verbose_name='공격자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.IntegerField(blank=True, choices=[(1, 1), (1, 1), (5, 5), (8, 8), (8, 8)], null=True, verbose_name='수비자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
