# Generated by Django 3.2.11 on 2022-01-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0002_alter_game_attacker_num_alter_game_defender_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.IntegerField(blank=True, choices=[(2, 2), (3, 3), (5, 5), (6, 6), (8, 8)], verbose_name='공격자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.IntegerField(blank=True, choices=[(4, 4), (4, 4), (4, 4), (4, 4), (9, 9)], null=True, verbose_name='수비자 선택'),
        ),
    ]
