# Generated by Django 3.2.11 on 2022-01-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0003_auto_20220121_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.IntegerField(blank=True, choices=[(1, 1), (3, 3), (5, 5), (8, 8), (9, 9)], verbose_name='공격자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (6, 6), (9, 9)], null=True, verbose_name='수비자 선택'),
        ),
    ]
