# Generated by Django 3.1.3 on 2022-01-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0003_auto_20220121_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.IntegerField(blank=True, choices=[(4, 4), (5, 5), (7, 7), (8, 8), (10, 10)], verbose_name='공격자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (3, 3), (3, 3)], null=True, verbose_name='수비자 선택'),
        ),
    ]
