# Generated by Django 4.0.1 on 2022-01-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0003_remove_user_point_alter_game_attacker_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.CharField(choices=[(3, 3), (4, 4), (5, 5), (8, 8), (11, 11)], max_length=2, verbose_name='공격자 선택 숫자'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (6, 6), (7, 7), (10, 10)], max_length=2, verbose_name='수비자 선택 숫자'),
        ),
    ]
