# Generated by Django 4.0.1 on 2022-01-21 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardgame', '0004_alter_game_attacker_alter_game_attacker_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack', to=settings.AUTH_USER_MODEL, verbose_name='공격자'),
        ),
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (5, 5), (7, 7), (9, 9)], verbose_name='공격자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='defend', to=settings.AUTH_USER_MODEL, verbose_name='수비자'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.IntegerField(blank=True, choices=[(1, 1), (4, 4), (5, 5), (8, 8), (9, 9)], null=True, verbose_name='수비자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='승자'),
        ),
    ]
