# Generated by Django 4.0.1 on 2022-01-20 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0004_alter_game_attacker_num_alter_game_defender_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.CharField(blank=True, choices=[(1, 1), (4, 4), (5, 5), (6, 6), (8, 8)], max_length=2, verbose_name='공격자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='defend', to=settings.AUTH_USER_MODEL, verbose_name='수비자'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.CharField(blank=True, choices=[(3, 3), (7, 7), (7, 7), (7, 7), (7, 7)], max_length=2, verbose_name='수비자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rule',
            field=models.CharField(blank=True, choices=[('BIG', 'BIG'), ('SMALL', 'SMALL')], max_length=5, verbose_name='승리 룰'),
        ),
    ]
