# Generated by Django 4.0.1 on 2022-01-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0005_alter_game_attacker_num_alter_game_defender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (4, 4), (5, 5), (9, 9)], max_length=2, verbose_name='공격자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.CharField(blank=True, choices=[(3, 3), (3, 3), (3, 3), (7, 7), (11, 11)], max_length=2, verbose_name='수비자 선택'),
        ),
    ]
