# Generated by Django 4.0.1 on 2022-01-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0007_alter_game_attacker_num_alter_game_defender_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.IntegerField(blank=True, choices=[(2, 2), (3, 3), (6, 6), (9, 9), (10, 10)], max_length=2, verbose_name='공격자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.IntegerField(blank=True, choices=[(5, 5), (7, 7), (7, 7), (7, 7), (7, 7)], max_length=2, verbose_name='수비자 선택'),
        ),
    ]
