# Generated by Django 3.2.11 on 2022-01-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0004_auto_20220121_1814'),
        ('cardgame', '0007_alter_game_attacker_num_alter_game_defender_num'),
    ]

    operations = [
    ]
