# Generated by Django 4.0.1 on 2022-01-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0008_alter_game_attacker_num_alter_game_defender_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attacker_num',
            field=models.IntegerField(blank=True, choices=[(1, 1), (5, 5), (7, 7), (8, 8), (10, 10)], verbose_name='공격자 선택'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender_num',
            field=models.IntegerField(blank=True, choices=[(2, 2), (2, 2), (2, 2), (6, 6), (9, 9)], verbose_name='수비자 선택'),
        ),
    ]
